### ISSUE TITLE
Latest portal fails to deploy on edrn-dev.nci.nih.gov

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#382]
## 🐛 Describe the Bug

CBIIT Jenkins cannot deploy latest P5 image to edrn-dev.nci.nih.gov

## 🖼 Screenshots

Log file shows:
```
16:58:08 👷‍♀️ Bring over latest production DB
16:58:09 NOTICE:  database "edrn" does not exist, skipping
16:58:10 /local/content/edrn/docker
16:58:10 compose.sh
16:58:10 docker-compose.yaml
16:58:10 edrn.sql.bz2
16:58:10 sync-from-ops.sh
16:58:11  set_config 
16:58:11 ------------
16:58:11  
16:58:11 (1 row)
16:58:11 
…
16:58:42  setval 
16:58:42 --------
16:58:42    1469
16:58:42 (1 row)
16:58:42 
16:58:42  setval 
16:58:42 --------
16:58:42      18
16:58:42 (1 row)
16:58:42 
16:58:42 ERROR:  could not create unique index "django_content_type_app_label_model_76bd3d3b_uniq"
16:58:42 DETAIL:  Key (app_label, model)=(wagtailcore, page) is duplicated.
16:58:42 STATEMENT:  ALTER TABLE ONLY public.django_content_type
16:58:42     ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);
16:58:42 ERROR:  could not create unique index "django_content_type_pkey"
16:58:42 DETAIL:  Key (id)=(1) is duplicated.
16:58:42 STATEMENT:  ALTER TABLE ONLY public.django_content_type
16:58:42     ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);
16:59:02 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:02 STATEMENT:  ALTER TABLE ONLY public.auth_permission
16:59:02     ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:02 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:02 STATEMENT:  ALTER TABLE ONLY public.django_admin_log
16:59:02     ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.taggit_taggeditem
16:59:03     ADD CONSTRAINT taggit_taggeditem_content_type_id_9957a03c_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_modellogentry
16:59:03     ADD CONSTRAINT wagtailcore_modellog_content_type_id_68849e77_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_page
16:59:03     ADD CONSTRAINT wagtailcore_page_content_type_id_c28424df_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_pagelogentry
16:59:03     ADD CONSTRAINT wagtailcore_pageloge_content_type_id_74e7708a_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_referenceindex
16:59:03     ADD CONSTRAINT wagtailcore_referenc_base_content_type_id_313cf40f_fk_django_co FOREIGN KEY (base_content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_referenceindex
16:59:03     ADD CONSTRAINT wagtailcore_referenc_content_type_id_766e0336_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_referenceindex
16:59:03     ADD CONSTRAINT wagtailcore_referenc_to_content_type_id_93690bbd_fk_django_co FOREIGN KEY (to_content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_revision
16:59:03     ADD CONSTRAINT wagtailcore_revision_base_content_type_id_5b4ef7bd_fk_django_co FOREIGN KEY (base_content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_revision
16:59:03     ADD CONSTRAINT wagtailcore_revision_content_type_id_c8cb69c0_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_task
16:59:03     ADD CONSTRAINT wagtailcore_task_content_type_id_249ab8ba_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_taskstate
16:59:03     ADD CONSTRAINT wagtailcore_taskstat_content_type_id_0a758fdc_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_workflowstate
16:59:03     ADD CONSTRAINT wagtailcore_workflow_base_content_type_id_a30dc576_fk_django_co FOREIGN KEY (base_content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_workflowstate
16:59:03     ADD CONSTRAINT wagtailcore_workflow_content_type_id_2bb78ce1_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:03 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:03 STATEMENT:  ALTER TABLE ONLY public.wagtailcore_workflowcontenttype
16:59:03     ADD CONSTRAINT wagtailcore_workflow_content_type_id_b261bb37_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:04 ERROR:  there is no unique constraint matching given keys for referenced table "django_content_type"
16:59:04 STATEMENT:  ALTER TABLE ONLY public.wagtailsearch_indexentry
16:59:04     ADD CONSTRAINT wagtailsearch_indexe_content_type_id_62ed694f_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
16:59:04 
16:59:04 📀 Initial database setup
16:59:12 /usr/lib/python3.11/site-packages/wagtail/contrib/modeladmin/apps.py:15: RemovedInWagtail60Warning: wagtail.contrib.modeladmin is deprecated. Use wagtail.snippets or the separate wagtail-modeladmin package instead.
16:59:12   warn(
16:59:13 Traceback (most recent call last):
16:59:13   File "/usr/bin/django-admin", line 8, in <module>
16:59:13     sys.exit(execute_from_command_line())
16:59:13              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
16:59:13     utility.execute()
16:59:13   File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
16:59:13     self.fetch_command(subcommand).run_from_argv(self.argv)
16:59:13   File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
16:59:13     self.execute(*args, **cmd_options)
16:59:13   File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 453, in execute
16:59:13     self.check()
16:59:13   File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
16:59:13     all_issues = checks.run_checks(
16:59:13                  ^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
16:59:13     new_errors = check(app_configs=app_configs, databases=databases)
16:59:13                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/django/core/checks/model_checks.py", line 36, in check_all_models
16:59:13     errors.extend(model.check(**kwargs))
16:59:13                   ^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/wagtail/models/__init__.py", line 3057, in check
16:59:13     outdated_objs = cls.objects._migrate_permission_type()
16:59:13                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/wagtail/models/__init__.py", line 2991, in _migrate_permission_type
16:59:13     content_type=get_default_page_content_type(),
16:59:13                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/wagtail/models/__init__.py", line 172, in get_default_page_content_type
16:59:13     return ContentType.objects.get_for_model(Page)
16:59:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/django/contrib/contenttypes/models.py", line 52, in get_for_model
16:59:13     ct = self.get(app_label=opts.app_label, model=opts.model_name)
16:59:13          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
16:59:13     return getattr(self.get_queryset(), name)(*args, **kwargs)
16:59:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:59:13   File "/usr/lib/python3.11/site-packages/django/db/models/query.py", line 640, in get
16:59:13     raise self.model.MultipleObjectsReturned(
16:59:13 django.contrib.contenttypes.models.ContentType.MultipleObjectsReturned: get() returned more than one ContentType -- it returned 2!
16:59:14 Build step 'Execute shell' marked build as failure
16:59:14 Sending e-mails to: sean.kelly@nih.gov
16:59:14 No emails were triggered.
16:59:14 Finished: FAILURE
```

**Comment by nutjob4life** [comment]
Well although this was reproducible three times in a row on 2024-12-11, as of 2024-12-19 it's worked.

I'm going to retry it a few more times just to see if it's somehow resolved itself.

**Comment by nutjob4life** [comment]
Unless @hoodriverheather or @elawsgh get NCI accounts there's no way to have third-party QC on this issue so adding `skip-qc` lavel

**Comment by nutjob4life** [comment]
Oh interesting, this may be related: https://github.com/wagtail/wagtail/issues/5918
