### ISSUE TITLE
Portal nightly ingest failing on publications

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#383]
## 🐛 Describe the Bug

In debugging #382, I noticed that the nightly ingest was failing. It gets to the publications step, encounters an error, and then aborts the rest.

## 📜 Stack Trace
```
Traceback (most recent call last):
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "ekeknowledge_publicationsubjecturi_identifier_key"
DETAIL:  Key (identifier)=(http://edrn.nci.nih.gov/data/pubs/794) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/src/eke.knowledge/src/eke/knowledge/publications.py", line 392, in associate_publication
    
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/wagtail/models/__init__.py", line 1464, in save
    result = super().save(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/modelcluster/models.py", line 205, in save
    getattr(self, relation).commit()
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/modelcluster/fields.py", line 223, in commit
    original_manager.add(item, bulk=False)
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 786, in add
    obj.save()
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P6/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: duplicate key value violates unique constraint "ekeknowledge_publicationsubjecturi_identifier_key"
DETAIL:  Key (identifier)=(http://edrn.nci.nih.gov/data/pubs/794) already exists.
```

## 🔎 Expected Behavior

Ingest should succeed.

**Comment by nutjob4life** [comment]
To do:

- [x] Fix (fixed in fc0089a819ade0fc20e046954d6f8482f4e52fa4)
- [ ] Test full ingest locally
- [ ] Test full ingest remotely

**Comment by nutjob4life** [comment]
Works fine but QC requires an ingest source to fail which seems unlikely :innocent
