### ISSUE TITLE
Standalone Ingest (`devrbuild` and Jenkins) fails

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#45]
## 🐛 Describe the Bug

Building a local dev env P5 fails during the ingest step. It also fails in Jenkins.

## 📜 How To Reproduce

Run `support/devrbuild.sh` with a call to `support/ingest.py`.

## 🔎 Expected Behavior

Ingest should succeed

## 🖼 Stacktrace

```
2020-06-19 20:14:23 ERROR root This is most unfortunate: ((<Item at /edrn/protocols/286-prostate-rapid-reference-set-application-brian>, <HTTPRequest, URL=http://foo>, None, <z3c.relationfield.schema.RelationChoice object at 0x10ca44050>, <SelectWidget 'principalInvestigator'>), <InterfaceClass z3c.form.interfaces.ITerms>, u'')
Traceback (most recent call last):
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P5/support/ingest.py", line 149, in main
    _main(app)
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P5/support/ingest.py", line 138, in _main
    _ingest(portal)
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P5/support/ingest.py", line 98, in _ingest
    ingestor.ingest()
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P5/src/eke.knowledge/src/eke/knowledge/sitefolder.py", line 230, in ingest
    people = self._ingestPeople(peopleStatements, sites)
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P5/src/eke.knowledge/src/eke/knowledge/sitefolder.py", line 173, in _ingestPeople
    person = self.createPerson(site, uri, predicates)
  File "/Users/kelly/Documents/Clients/JPL/Cancer/Portal/Development/P5/src/eke.knowledge/src/eke/knowledge/sitefolder.py", line 144, in createPerson
    personID=urlparse.urlparse(unicode(identifier)).path.split(u'/')[-1]
  File "/Users/kelly/.buildout/eggs/plone.dexterity-2.6.2-py2.7.egg/plone/dexterity/utils.py", line 203, in createContentInContainer
    checkConstraints=checkConstraints
  File "/Users/kelly/.buildout/eggs/plone.dexterity-2.6.2-py2.7.egg/plone/dexterity/utils.py", line 189, in addContentToContainer
    newName = container._setObject(name, object)
  File "/Users/kelly/.buildout/eggs/Products.BTreeFolder2-2.14.0-py2.7.egg/Products/BTreeFolder2/BTreeFolder2.py", line 461, in _setObject
    notify(ObjectAddedEvent(ob, self, id))
  File "/Users/kelly/.buildout/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/kelly/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/Users/kelly/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 139, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/kelly/.buildout/eggs/zope.interface-4.4.3-py2.7-macosx-10.14-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/kelly/.buildout/eggs/zope.interface-4.4.3-py2.7-macosx-10.14-x86_64.egg/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "/Users/kelly/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/event.py", line 36, in objectEventNotify
    component_subscribers((event.object, event), None)
  File "/Users/kelly/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 139, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/kelly/.buildout/eggs/zope.interface-4.4.3-py2.7-macosx-10.14-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/kelly/.buildout/eggs/zope.interface-4.4.3-py2.7-macosx-10.14-x86_64.egg/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/CMFCatalogAware.py", line 266, in handleContentishEvent
    ob.notifyWorkflowCreated()
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/CMFCatalogAware.py", line 192, in notifyWorkflowCreated
    wftool.notifyCreated(self)
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/WorkflowTool.py", line 289, in notifyCreated
    self._reindexWorkflowVariables(ob)
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/WorkflowTool.py", line 639, in _reindexWorkflowVariables
    ob.reindexObjectSecurity()
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/CMFCatalogAware.py", line 103, in reindexObjectSecurity
    for brain in catalog.unrestrictedSearchResults(path=path):
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/CatalogTool.py", line 260, in unrestrictedSearchResults
    processQueue()
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/indexing.py", line 91, in processQueue
    processed = queue.process()
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/indexing.py", line 220, in process
    util.reindex(obj, attributes, update_metadata=metadata)
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/indexing.py", line 46, in reindex
    update_metadata=update_metadata
  File "/Users/kelly/.buildout/eggs/Products.CMFCore-2.2.12-py2.7.egg/Products/CMFCore/CatalogTool.py", line 359, in _reindexObject
    self.catalog_object(object, uid, idxs, update_metadata)
  File "/Users/kelly/.buildout/eggs/Products.CMFPlone-5.1.5-py2.7.egg/Products/CMFPlone/CatalogTool.py", line 421, in catalog_object
    update_metadata, pghandler=pghandler)
  File "/Users/kelly/.buildout/eggs/Products.ZCatalog-3.0.3-py2.7.egg/Products/ZCatalog/ZCatalog.py", line 476, in catalog_object
    update_metadata=update_metadata)
  File "/Users/kelly/.buildout/eggs/Products.ZCatalog-3.0.3-py2.7.egg/Products/ZCatalog/Catalog.py", line 360, in catalogObject
    blah = x.index_object(index, object, threshold)
  File "/Users/kelly/.buildout/eggs/Products.ZCTextIndex-2.13.5-py2.7-macosx-10.14-x86_64.egg/Products/ZCTextIndex/ZCTextIndex.py", line 180, in index_object
    text = getattr(obj, attr, None)
  File "/Users/kelly/.buildout/eggs/plone.indexer-1.0.5-py2.7.egg/plone/indexer/wrapper.py", line 65, in __getattr__
    return indexer()
  File "/Users/kelly/.buildout/eggs/plone.indexer-1.0.5-py2.7.egg/plone/indexer/delegate.py", line 20, in __call__
    return self.callable(self.context)
  File "/Users/kelly/.buildout/eggs/collective.dexteritytextindexer-2.2.1-py2.7.egg/collective/dexteritytextindexer/indexer.py", line 69, in dynamic_searchable_text_indexer
    widget = get_field_widget(obj, form_field, request)
  File "/Users/kelly/.buildout/eggs/collective.dexteritytextindexer-2.2.1-py2.7.egg/collective/dexteritytextindexer/indexer.py", line 142, in get_field_widget
    widget.update()
  File "/Users/kelly/.buildout/eggs/z3c.form-3.6-py2.7.egg/z3c/form/browser/select.py", line 51, in update
    super(SelectWidget, self).update()
  File "/Users/kelly/.buildout/eggs/z3c.form-3.6-py2.7.egg/z3c/form/browser/widget.py", line 171, in update
    super(HTMLFormElement, self).update()
  File "/Users/kelly/.buildout/eggs/z3c.form-3.6-py2.7.egg/z3c/form/widget.py", line 233, in update
    self.updateTerms()
  File "/Users/kelly/.buildout/eggs/z3c.form-3.6-py2.7.egg/z3c/form/widget.py", line 227, in updateTerms
    interfaces.ITerms)
  File "/Users/kelly/.buildout/eggs/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 112, in getMultiAdapter
    raise ComponentLookupError(objects, interface, name)
ComponentLookupError: ((<Item at /edrn/protocols/286-prostate-rapid-reference-set-application-brian>, <HTTPRequest, URL=http://foo>, None, <z3c.relationfield.schema.RelationChoice object at 0x10ca44050>, <SelectWidget 'principalInvestigator'>), <InterfaceClass z3c.form.interfaces.ITerms>, u'')
```

**Comment by nutjob4life** [comment]
Strangely this is happening only outside of running a Zope instance. Doing `zope -O edrn run …` doesn't help. I've ingested 83 times today already (inside of Zope) so it can't be bad RDF data.

**Comment by nutjob4life** [comment]
@hoodriverheather to confirm this is closed, try:

1. Visit https://edrn-dev.jpl.nasa.gov/jenkins/
2. Click "log in" and log in with JPL username and password.
3. In the row with "EDRN-P5", click the "Build Now" icon (looks like a 🕥 with a green ▶ overlaid on it)
4. Wait 1 hour and 30 minutes or so
5. Return to https://edrn-dev.jpl.nasa.gov/jenkins/
6. Confirm there is a ☀️ to the left of "EDRN-P5".
7. Visit https://edrn-dev.jpl.nasa.gov/portal/5/dev/
8. Confirm that the dev site is up and has data

If steps 6 or 8 don't jive with reality, please re-open the issue 😵
