### ISSUE TITLE
Portal cannot ingest from BMDB

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#64]
## 🐛 Describe the Bug

When the portal attempts to ingest from the new live BMDB RDF, it encounters an error: `URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>`.

## 📜 How To Reproduce

Ingest biomarkers.

## 🔎 Expected Behavior

Successful ingest.

## 🖼 Screenshots

```console
ERROR:root:This is most unfortunate: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Traceback (most recent call last):
  File "<http://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/ws/support/ingest.py",> line 152, in main
    _main(app)
  File "<http://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/ws/support/ingest.py",> line 140, in _main
    _ingest(portal)
  File "<http://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/ws/support/ingest.py",> line 96, in _ingest
    ingestor.ingest()
  File "/data/local/edrn/portal/p5/src/eke.knowledge/src/eke/knowledge/base.py", line 154, in ingest
    statements.update(self.readRDF(rdfDataSource))
  File "/data/local/edrn/portal/p5/src/eke.knowledge/src/eke/knowledge/base.py", line 137, in readRDF
    graph.parse(url)
  File "/data/local/edrn/.buildout/eggs/rdflib-4.2.2-py2.7.egg/rdflib/graph.py", line 1030, in parse
    data=data, format=format)
  File "/data/local/edrn/.buildout/eggs/rdflib-4.2.2-py2.7.egg/rdflib/parser.py", line 186, in create_input_source
    input_source = URLInputSource(absolute_location, format)
  File "/data/local/edrn/.buildout/eggs/rdflib-4.2.2-py2.7.egg/rdflib/parser.py", line 106, in __init__
    file = urlopen(req)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/python-2.7.10/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

## 🕵️‍♀️ Extra Details

See https://github.com/EDRN/biomarker-database/issues/9

**Comment by nutjob4life** [comment]
No longer an issue; ingests seem to work all right
