### ISSUE TITLE
Stack trace when ingesting publications

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#65]
## 🐛 Describe the Bug

RDF Ingest fails on P5 during publication cleanup:

```console
WARNING:eke.knowledge.publicationfolder:PubMedID 18089831 already represented by publication http://edrn.jpl.nasa.gov/bmdb/publications/view/32; but making a duplicate anyway
WARNING:eke.knowledge.publicationfolder:PubMedID 21804560 already represented by publication http://edrn.nci.nih.gov/data/pubs/2149; but making a duplicate anyway
ERROR:root:This is most unfortunate: u'http://edrn.nci.nih.gov/data/pubs/1458'
Traceback (most recent call last):
  File "<http://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/ws/support/ingest.py",> line 152, in main
    _main(app)
  File "<http://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/ws/support/ingest.py",> line 140, in _main
    _ingest(portal)
  File "<http://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/ws/support/ingest.py",> line 96, in _ingest
    ingestor.ingest()
  File "/data/local/edrn/portal/p5/src/eke.knowledge/src/eke/knowledge/publicationfolder.py", line 225, in ingest
    subjectURItoPMIDs = self.filterExistingPublications(subjectURItoPMIDs)
  File "/data/local/edrn/portal/p5/src/eke.knowledge/src/eke/knowledge/publicationfolder.py", line 109, in filterExistingPublications
    del subjectURItoPMIDs[f.identifier]
KeyError: u'http://edrn.nci.nih.gov/data/pubs/1458'
Build step 'Execute shell' marked build as failure
```

## 🔎 Expected Behavior

Ingest should complete without error

## 🕵️‍♀️ Extra Details

See https://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/192/

**Comment by nutjob4life** [comment]
This seems to be caused by a DMCC publication, #1458, that uses PubMedID 18310059, but a second publication, #1468, has appeared that also uses PubMedID 18310059.

In the DMCC data, these seem to be different publications:

**#1458**
- site = 5
- title = Evaluation of the branched-chain DNA assay for measurement of RNA in formalin-fixed tissues
- journal = Journal of Molecular Diagnostics
- PubMedID = 18310059

**#1468**
- site = 5
- title = Bias-reduced estimators and confidence intervals for odds ratios in genome-wide association studies
- journal = Biostatistics
- PubMedID = 18310059
