### ISSUE TITLE
Publication ingest failed with data from Entrez Publication search

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#75]
## 🐛 Describe the Bug

Publication ingest suddenly failing again, missing PubMed data.

## 🖼 Stacktrace

```console
ERROR:root:This is most unfortunate: u'ISOAbbreviation'
Traceback (most recent call last):
  File "/usr/local/edrn/portal/p5/support/ingest.py", line 152, in main
    _main(app)
  File "/usr/local/edrn/portal/p5/support/ingest.py", line 140, in _main
    _ingest(portal)
  File "/usr/local/edrn/portal/p5/support/ingest.py", line 96, in _ingest
    ingestor.ingest()
  File "/data/local/edrn/portal/p5/src/eke.knowledge/src/eke/knowledge/publicationfolder.py", line 230, in ingest
    created = self.createMissingPublications(subjectURItoPMIDs)
  File "/data/local/edrn/portal/p5/src/eke.knowledge/src/eke/knowledge/publicationfolder.py", line 174, in createMissingPublications
    pub.journal = unicode(medline[u'MedlineCitation'][u'Article'][u'Journal'][u'ISOAbbreviation'])
KeyError: u'ISOAbbreviation'
```

**Comment by nutjob4life** [comment]
Confirmed fixed
