### ISSUE TITLE
Stack trace when upgrading

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#93]
## 🐛 Describe the Bug

[Jenkins build 380](https://edrn-dev.jpl.nasa.gov/jenkins/job/EDRN-P5/380/) gave this stack trace when it ran the P5 upgrade to 5.1.0:

```console
ERROR:root:This is most unfortunate: Missing required parameter(s): source
Traceback (most recent call last):
  File "/usr/local/edrn/portal/p5/support/upgradeEDRN.py", line 80, in main
    _main(app)
  File "/usr/local/edrn/portal/p5/support/upgradeEDRN.py", line 69, in _main
    upgradeEDRN(portal)
  File "/usr/local/edrn/portal/p5/support/upgradeEDRN.py", line 56, in upgradeEDRN
    qi.upgrade_product(productID)
  File "/data/local/edrn/.buildout/eggs/Products.CMFPlone-5.2.2-py2.7.egg/Products/CMFPlone/controlpanel/browser/quickinstaller.py", line 399, in upgrade_product
    self.ps.upgradeProfile(profile['id'])
  File "/data/local/edrn/.buildout/eggs/Products.GenericSetup-2.0.2-py2.7.egg/Products/GenericSetup/tool.py", line 1156, in upgradeProfile
    step.doStep(self)
  File "/data/local/edrn/.buildout/eggs/Products.GenericSetup-2.0.2-py2.7.egg/Products/GenericSetup/upgrade.py", line 168, in doStep
    self.handler(tool)
  File "/data/local/edrn/portal/p5/src/edrnsite.policy/src/edrnsite/policy/upgrades.py", line 195, in install202SOWMenus
    installDropDownMenus(portal)
  File "/data/local/edrn/portal/p5/src/edrnsite.policy/src/edrnsite/policy/dropDownMenus.py", line 322, in install
    archive = archiveStuff(portal)
  File "/data/local/edrn/portal/p5/src/edrnsite.policy/src/edrnsite/policy/content_reorg.py", line 62, in archiveStuff
    archive('/resources/edrnLabCASUserGuide31081714326.pdf')
  File "/data/local/edrn/portal/p5/src/edrnsite.policy/src/edrnsite/policy/content_reorg.py", line 19, in archive
    pac.move(source=pac.get(path), target=archiveFolder)
  File "<decorator-gen-13>", line 2, in move
  File "/data/local/edrn/.buildout/eggs/plone.api-1.10.2-py2.7.egg/plone/api/validation.py", line 77, in wrapped
    params=', '.join(missing),
MissingParameterError: Missing required parameter(s): source
```

**Comment by nutjob4life** [comment]
Ahh, it's related to @hoodriverheather's removal of edrnLabCASUserGuide31081714326.pdf. No problem!
